site_name: finance-rl
site_description: Liquidation of assets environment.
site_author: Juan Carlos Calvo

repo_url: https://github.com/juan-carlos-calvo/finance-rl
edit_uri: https://github.com/juan-carlos-calvo/finance-rl/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
